global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'my-project'


scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets:
          - prometheus:9090
          - cadvisor:8080
          - node-exporter:9100

  - job_name: 'prometheus-application'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - monitoring-demo:9090

  - job_name: 'blackbox-tester-https-test'
    metrics_path: /probe
    params:
      module: [ custom_https ]  # Look for a HTTP 200 response.
    scrape_interval: 30s
    static_configs:
      - targets:
          - https://monitoring-demo/api/health/status
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox:9115"

