version: "3.7"
services:
  monitoring-demo:
    image: croudsarabi/monitoring-demo:latest
    labels:
      # - com.centurylinklabs.watchtower.scope=application
      - monitoring-demo.container.importance=critical
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE= postgres, drop-first
    networks:
      default:

  monitoring-demo-db:
    image: postgres
    labels:
      #- com.centurylinklabs.watchtower.scope=infrastructure
      - monitoring-demo.container.importance=critical
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${MONITORING_DEMO_DB_PASSWORD}
      POSTGRES_USER: ${MONITORING_DEMO_DB_USER}
      POSTGRES_DB: ${MONITORING_DEMO_DB_NAME}
    #    ports:
    #      - 5432:5432
    volumes:
      - monitoringdemodb:/var/lib/postgresql/data
    networks:
      default:

networks:
  default:

volumes:
  monitoringdemodb:
